# Generated by Django 5.1.5 on 2025-01-24 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='Category ID from the original dataset')),
                ('name', models.CharField(max_length=32, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('icon_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Icon name')),
            ],
        ),
        migrations.CreateModel(
            name='GiftoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='System user')),
                ('hobbies', models.ManyToManyField(to='gifto.hobby', verbose_name='Hobbies')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=10, verbose_name='ASIN code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('image_url', models.TextField(blank=True, null=True, verbose_name='Image URL')),
                ('product_url', models.TextField(blank=True, null=True, verbose_name='Amazon URL')),
                ('stars', models.PositiveIntegerField(blank=True, null=True, verbose_name='10x Star rating')),
                ('price', models.PositiveIntegerField(verbose_name='Item price in cents')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Amazon bestseller/choice')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifto.category', verbose_name='Category')),
            ],
        ),
    ]
