# Generated by Django 5.1.5 on 2025-01-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='giftouser',
            options={'verbose_name': 'Gifto User', 'verbose_name_plural': 'Gifto Users'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'Hobby', 'verbose_name_plural': 'Hobbies'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.BooleanField(verbose_name='Approve/reject decision')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifto.category', verbose_name='Category this feedback refers to')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifto.giftouser', verbose_name='User who submitted this feedback')),
            ],
        ),
    ]
