# Generated by Django 5.1.5 on 2025-01-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifto', '0002_alter_category_options_alter_giftouser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Category name'),
        ),
    ]
