# Generated by Django 5.1.5 on 2025-01-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifto', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Slug'),
        ),
    ]
