# Generated by Django 5.1.5 on 2025-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifto', '0004_hobby_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
    ]
